hssi_afu Class Reference
#include </root/samples/hssi/hssi_afu.h>
Public Member Functions
hssi_afu ()
std::string ethernet_interface ()
void mbox_write (uint16_t offset, uint32_t data)
uint32_t mbox_read (uint16_t offset)
Detailed Description
Definition at line 54 of file hssi_afu.h.
Constructor & Destructor Documentation
hssi_afu()
hssi_afu::hssi_afu () [inline]
Definition at line 56 of file hssi_afu.h.
Member Function Documentation
ethernet_interface()
std::string hssi_afu::ethernet_interface () [inline]
Definition at line 60 of file hssi_afu.h.
References opae::fpga::types::properties::get().
Referenced by hssi_100g_cmd::run(), and hssi_10g_cmd::run().
mbox_write()
void hssi_afu::mbox_write (uint16_t offset, uint32_t data) [inline]
Definition at line 95 of file hssi_afu.h.
References ACK_TRANS, AFU_CMD_SHIFT, NO_TIMEOUT, TRAFFIC_CTRL_CMD, TRAFFIC_CTRL_DATA, WRITE_CMD, and WRITE_DATA_SHIFT.
Referenced by hssi_100g_cmd::run(), and hssi_10g_cmd::run().
mbox_read()
uint32_t hssi_afu::mbox_read (uint16_t offset) [inline]
Definition at line 148 of file hssi_afu.h.
References ACK_TRANS, AFU_CMD_SHIFT, NO_TIMEOUT, READ_CMD, TRAFFIC_CTRL_CMD, and TRAFFIC_CTRL_DATA.
Referenced by hssi_100g_cmd::print_registers(), hssi_10g_cmd::print_registers(), and hssi_10g_cmd::run().