CSR_MGR Class Reference
#include </root/samples/base/sw/csr_mgr.h>
Public Types
enum t_csr_common {
CSR_COMMON_DFH = 0,
CSR_COMMON_ID_L = 1,
CSR_COMMON_ID_H = 2,
CSR_COMMON_FREQ = 8,
CSR_COMMON_CACHE_RD_HITS = 9,
CSR_COMMON_CACHE_WR_HITS = 10,
CSR_COMMON_VL0_RD_LINES = 11,
CSR_COMMON_VL0_WR_LINES = 12,
CSR_COMMON_VH0_LINES = 13,
CSR_COMMON_VH1_LINES = 14,
CSR_COMMON_FIU_STATE = 15,
CSR_COMMON_RD_ALMOST_FULL_CYCLES = 16,
CSR_COMMON_WR_ALMOST_FULL_CYCLES = 17,
CSR_COMMON__LAST = 18
 }
Public Member Functions
CSR_MGR (SVC_WRAPPER &svc)
~CSR_MGR ()
void writeCSR (uint32_t idx, uint64_t v)
uint64_t readCSR (uint32_t idx)
uint64_t readCommonCSR (t_csr_common idx)
uint64_t getAFUMHz (uint64_t uClk_usr_mhz=0)
Protected Types
enum { USER_CSR_BASE = 32
 }
Protected Attributes
SVC_WRAPPER & svc
Detailed Description
Definition at line 39 of file csr_mgr.h.
Member Enumeration Documentation
anonymous enum
anonymous enum [protected]
Enumerator
USER_CSR_BASE
Definition at line 42 of file csr_mgr.h.
t_csr_common
enum CSR_MGR::t_csr_common
Enumerator
CSR_COMMON_DFH
CSR_COMMON_ID_L
CSR_COMMON_ID_H
CSR_COMMON_FREQ
CSR_COMMON_CACHE_RD_HITS
CSR_COMMON_CACHE_WR_HITS
CSR_COMMON_VL0_RD_LINES
CSR_COMMON_VL0_WR_LINES
CSR_COMMON_VH0_LINES
CSR_COMMON_VH1_LINES
CSR_COMMON_FIU_STATE
CSR_COMMON_RD_ALMOST_FULL_CYCLES
CSR_COMMON_WR_ALMOST_FULL_CYCLES
CSR_COMMON__LAST
Definition at line 74 of file csr_mgr.h.
Constructor & Destructor Documentation
CSR_MGR()
CSR_MGR::CSR_MGR (SVC_WRAPPER & svc) [inline]
Definition at line 54 of file csr_mgr.h.
 CSR_MGR()
CSR_MGR::~CSR_MGR () [inline]
Definition at line 56 of file csr_mgr.h.
Member Function Documentation
writeCSR()
void CSR_MGR::writeCSR (uint32_t idx, uint64_t v) [inline]
Definition at line 62 of file csr_mgr.h.
References svc, and USER_CSR_BASE.
Referenced by main().
readCSR()
uint64_t CSR_MGR::readCSR (uint32_t idx) [inline]
Definition at line 66 of file csr_mgr.h.
References svc, and USER_CSR_BASE.
readCommonCSR()
uint64_t CSR_MGR::readCommonCSR (t_csr_common idx) [inline]
Definition at line 99 of file csr_mgr.h.
References CSR_COMMON__LAST, and svc.
Referenced by getAFUMHz().
getAFUMHz()
uint64_t CSR_MGR::getAFUMHz (uint64_t uClk_usr_mhz = 0) [inline]
Definition at line 111 of file csr_mgr.h.
References CSR_COMMON_FREQ, and readCommonCSR().
Referenced by main().
Field Documentation
svc
SVC_WRAPPER& CSR_MGR::svc [protected]
Definition at line 126 of file csr_mgr.h.
Referenced by readCommonCSR(), readCSR(), and writeCSR().