OPAE_SVC_WRAPPER Class Reference
#include </root/samples/base/sw/opae_svc_wrapper.h>
Public Member Functions
OPAE_SVC_WRAPPER (const char *accel_uuid)
~OPAE_SVC_WRAPPER ()
bool isOk (void) const
bool hwIsSimulated (void) const
fpga_result mmioWrite64 (uint32_t idx, uint64_t v)
uint64_t mmioRead64 (uint32_t idx)
void * allocBuffer (size_t nBytes, uint64_t *ioAddress=NULL)
void freeBuffer (void *va)
Data Fields
mpf_handle_t mpf_handle
Protected Attributes
fpga_handle accel_handle
bool is_ok
bool is_simulated
Private Member Functions
fpga_result findAndOpenAccel (const char *accel_uuid)
bool probeForASE ()
Detailed Description
Definition at line 39 of file opae_svc_wrapper.h.
Constructor & Destructor Documentation
OPAE_SVC_WRAPPER()
OPAE_SVC_WRAPPER::OPAE_SVC_WRAPPER (const char * accel_uuid)
Definition at line 43 of file opae_svc_wrapper.cpp.
References findAndOpenAccel(), FPGA_OK, is_ok, is_simulated, and probeForASE().
 OPAE_SVC_WRAPPER()
OPAE_SVC_WRAPPER::~OPAE_SVC_WRAPPER ()
Definition at line 64 of file opae_svc_wrapper.cpp.
References accel_handle, fpgaClose(), fpgaUnmapMMIO(), and mpf_handle.
Member Function Documentation
isOk()
bool OPAE_SVC_WRAPPER::isOk (void) const [inline]
Definition at line 54 of file opae_svc_wrapper.h.
References is_ok.
Referenced by main().
hwIsSimulated()
bool OPAE_SVC_WRAPPER::hwIsSimulated (void) const [inline]
Definition at line 57 of file opae_svc_wrapper.h.
References is_simulated.
Referenced by main().
mmioWrite64()
fpga_result OPAE_SVC_WRAPPER::mmioWrite64 (uint32_t idx, uint64_t v) [inline]
Definition at line 62 of file opae_svc_wrapper.h.
References accel_handle, and fpgaWriteMMIO64().
mmioRead64()
uint64_t OPAE_SVC_WRAPPER::mmioRead64 (uint32_t idx) [inline]
Definition at line 66 of file opae_svc_wrapper.h.
References accel_handle, FPGA_OK, and fpgaReadMMIO64().
allocBuffer()
void * OPAE_SVC_WRAPPER::allocBuffer (size_t nBytes, uint64_t * ioAddress = NULL)
Definition at line 73 of file opae_svc_wrapper.cpp.
References accel_handle, FPGA_OK, fpgaGetIOAddress(), fpgaPrepareBuffer(), and mpf_handle.
Referenced by main().
freeBuffer()
void OPAE_SVC_WRAPPER::freeBuffer (void * va)
Definition at line 119 of file opae_svc_wrapper.cpp.
References mpf_handle.
findAndOpenAccel()
fpga_result OPAE_SVC_WRAPPER::findAndOpenAccel (const char * accel_uuid) [private]
Definition at line 132 of file opae_svc_wrapper.cpp.
References accel_handle, FPGA_ACCELERATOR, FPGA_NO_MEMORY, FPGA_NOT_FOUND, FPGA_OK, fpgaDestroyProperties(), fpgaDestroyToken(), fpgaEnumerate(), fpgaGetProperties(), fpgaMapMMIO(), fpgaOpen(), fpgaPropertiesSetGUID(), fpgaPropertiesSetObjectType(), and mpf_handle.
Referenced by OPAE_SVC_WRAPPER().
probeForASE()
bool OPAE_SVC_WRAPPER::probeForASE () [private]
Definition at line 213 of file opae_svc_wrapper.cpp.
References FPGA_DEVICE, FPGA_OK, fpgaDestroyProperties(), fpgaDestroyToken(), fpgaEnumerate(), fpgaGetProperties(), fpgaPropertiesGetDeviceID(), and fpgaPropertiesSetObjectType().
Referenced by OPAE_SVC_WRAPPER().
Field Documentation
accel_handle
fpga_handle OPAE_SVC_WRAPPER::accel_handle [protected]
Definition at line 43 of file opae_svc_wrapper.h.
Referenced by allocBuffer(), findAndOpenAccel(), mmioRead64(), mmioWrite64(), and ~OPAE_SVC_WRAPPER().
mpf_handle
mpf_handle_t OPAE_SVC_WRAPPER::mpf_handle
Definition at line 46 of file opae_svc_wrapper.h.
Referenced by allocBuffer(), findAndOpenAccel(), freeBuffer(), and ~OPAE_SVC_WRAPPER().
is_ok
bool OPAE_SVC_WRAPPER::is_ok [protected]
Definition at line 88 of file opae_svc_wrapper.h.
Referenced by isOk(), and OPAE_SVC_WRAPPER().
is_simulated
bool OPAE_SVC_WRAPPER::is_simulated [protected]
Definition at line 89 of file opae_svc_wrapper.h.
Referenced by hwIsSimulated(), and OPAE_SVC_WRAPPER().