samples/hello_mpf_afu/sw/hello_mpf_afu.cpp File Reference
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>
#include <assert.h>
#include <iostream>
#include <string>
#include `opae_svc_wrapper.h`
#include `csr_mgr.h`
#include `afu_json_info.h`
Functions
int main (void)
Function Documentation
main()
int main (void)
Definition at line 47 of file hello_mpf_afu.cpp.
References AFU_ACCEL_UUID, OPAE_SVC_WRAPPER::allocBuffer(), CL, CSR_MGR::getAFUMHz(), OPAE_SVC_WRAPPER::hwIsSimulated(), OPAE_SVC_WRAPPER::isOk(), and CSR_MGR::writeCSR().