samples/hello_events/hello_events.c File Reference
A code sample of using OPAE event API.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <getopt.h>
#include <poll.h>
#include <errno.h>
#include <sys/stat.h>
#include <pthread.h>
#include <opae/fpga.h>
Data Structures
struct ras_inject_error
struct events_config
struct events_config::target
union ras_inject_error.__unnamed__
struct ras_inject_error.__unnamed__.__unnamed__
Macros
#define FME_SYSFS_INJECT_ERROR `errors/inject_errors`
#define ON_ERR_GOTO(res, label, desc)
#define GETOPT_STRING `B:v`
Functions
int usleep (unsigned)
void print_err (const char *s, fpga_result res)
fpga_result inject_ras_fatal_error (fpga_token fme_token, uint8_t err)
void * error_thread (void *arg)
fpga_result parse_args (int argc, char *argv[])
fpga_result find_fpga (fpga_token *fpga, uint32_t *num_matches)
fpga_result get_bus (fpga_token tok, uint8_t *bus)
int main (int argc, char *argv[])
Variables
struct events_config events_config
Detailed Description
A code sample of using OPAE event API.
This sample starts two processes. One process injects an artificial fatal error to sysfs; while the other tries to asynchronously capture and handle the event. This sample code exercises all major functions of the event API, including creating and destroying event handles, register and unregister events, polling on event file descriptor, and getting the OS object associated with an event. For a full discussion of OPAE event API, refer to event.h.
Data Structure Documentation
struct ras_inject_error
Definition at line 74 of file hello_events.c.
Data Fields
union ras_inject_error
__unnamed__
struct events_config
Definition at line 92 of file hello_events.c.
Data Fields
struct target
target
struct events_config::target
Definition at line 93 of file hello_events.c.
Data Fields
int
bus
union ras_inject_error.__unnamed__
Definition at line 75 of file hello_events.c.
Data Fields
uint64_t
csr
__unnamed__
__unnamed__
struct ras_inject_error.__unnamed__.__unnamed__
Definition at line 77 of file hello_events.c.
Data Fields
uint64_t
catastrophicr_error: 1
uint64_t
fatal_error: 1
uint64_t
nonfatal_error: 1
uint64_t
rsvd: 61
Macro Definition Documentation
FME_SYSFS_INJECT_ERROR
#define FME_SYSFS_INJECT_ERROR `errors/inject_errors`
Definition at line 58 of file hello_events.c.
ON_ERR_GOTO
#define ON_ERR_GOTO(res, label, desc)
Value:
   do { \
      if ((res) != FPGA_OK) { \
         print_err((desc), (res)); \
         goto label; \
      } \
   } while (0)
Definition at line 60 of file hello_events.c.
GETOPT_STRING
#define GETOPT_STRING `B:v`
Definition at line 162 of file hello_events.c.
Function Documentation
usleep()
int usleep (unsigned)
Referenced by error_thread().
print_err()
void print_err (const char * s, fpga_result res)
Definition at line 68 of file hello_events.c.
References fpgaErrStr().
Referenced by error_thread().
inject_ras_fatal_error()
fpga_result inject_ras_fatal_error (fpga_token fme_token, uint8_t err)
Definition at line 104 of file hello_events.c.
References FME_SYSFS_INJECT_ERROR, FPGA_OK, FPGA_OPEN_SHARED, fpgaClose(), fpgaDestroyObject(), fpgaHandleGetObject(), fpgaObjectWrite64(), fpgaOpen(), ON_ERR_GOTO, and OPAE_ERR.
Referenced by error_thread().
error_thread()
void* error_thread (void * arg)
Definition at line 139 of file hello_events.c.
References FPGA_OK, inject_ras_fatal_error(), print_err(), and usleep().
Referenced by main().
parse_args()
fpga_result parse_args (int argc, char * argv[])
Definition at line 163 of file hello_events.c.
References events_config::target::bus, FPGA_EXCEPTION, FPGA_OK, GETOPT_STRING, and events_config::target.
Referenced by main().
find_fpga()
fpga_result find_fpga (fpga_token * fpga, uint32_t * num_matches)
Definition at line 210 of file hello_events.c.
References events_config::target::bus, FPGA_DEVICE, FPGA_OK, fpgaDestroyProperties(), fpgaEnumerate(), fpgaGetProperties(), fpgaPropertiesSetBus(), fpgaPropertiesSetObjectType(), ON_ERR_GOTO, and events_config::target.
Referenced by main().
get_bus()
fpga_result get_bus (fpga_token tok, uint8_t * bus)
Definition at line 240 of file hello_events.c.
References FPGA_OK, fpgaDestroyProperties(), fpgaGetProperties(), fpgaPropertiesGetBus(), and ON_ERR_GOTO.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 259 of file hello_events.c.
References error_thread(), find_fpga(), FPGA_EVENT_ERROR, FPGA_EXCEPTION, FPGA_NOT_FOUND, FPGA_OK, FPGA_OPEN_SHARED, fpgaClose(), fpgaCreateEventHandle(), fpgaDestroyEventHandle(), fpgaDestroyToken(), fpgaGetOSObjectFromEventHandle(), fpgaOpen(), fpgaRegisterEvent(), fpgaUnregisterEvent(), get_bus(), ON_ERR_GOTO, and parse_args().
Variable Documentation
events_config
struct events_config events_config
Initial value:
= {
   .target = {
      .bus = -1
   }
}