samples/hello_fpga/hello_fpga.c File Reference
A code sample illustrates the basic usage of the OPAE C API.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <getopt.h>
#include <unistd.h>
#include <uuid/uuid.h>
#include <opae/fpga.h>
Data Structures
struct cache_line
struct config
struct config::target
Macros
#define TEST_TIMEOUT 30000
#define CL(x) ((x) * 64)
#define LOG2_CL 6
#define MB(x) ((x) * 1024 * 1024)
#define CACHELINE_ALIGNED_ADDR(p) ((p) >> LOG2_CL)
#define LPBK1_BUFFER_SIZE MB(1)
#define LPBK1_BUFFER_ALLOCATION_SIZE MB(2)
#define LPBK1_DSM_SIZE MB(2)
#define CSR_SRC_ADDR 0x0120
#define CSR_DST_ADDR 0x0128
#define CSR_CTL 0x0138
#define CSR_STATUS1 0x0168
#define CSR_CFG 0x0140
#define CSR_NUM_LINES 0x0130
#define DSM_STATUS_TEST_COMPLETE 0x40
#define CSR_AFU_DSM_BASEL 0x0110
#define NLB0_AFUID `D8424DC4-A4A3-C413-F89E-433683F9040B`
#define N3000_AFUID `9AEFFE5F-8457-0612-C000-C9660D824272`
#define FPGA_NLB0_UUID_H 0xd8424dc4a4a3c413
#define FPGA_NLB0_UUID_L 0xf89e433683f9040b
#define ON_ERR_GOTO(res, label, desc)
#define GETOPT_STRING `B:scv`
Functions
int usleep (unsigned)
void print_err (const char *s, fpga_result res)
fpga_result parse_args (int argc, char *argv[])
fpga_result find_fpga (fpga_guid afu_guid, fpga_token *accelerator_token, uint32_t *num_matches_accelerators)
fpga_result get_bus (fpga_token tok, uint8_t *bus)
bool probe_for_ase (void)
fpga_result find_nlb_n3000 (fpga_handle accelerator_handle, uint64_t *afu_baddr)
int main (int argc, char *argv[])
Variables
struct config config
Detailed Description
A code sample illustrates the basic usage of the OPAE C API.
The sample is a host application that demonstrates the basic steps of interacting with FPGA using the OPAE library. These steps include:
FPGA enumeration
Resource acquiring and releasing
Managing shared memory buffer
MMIO read and write
The sample also demonstrates OPAE's object model, such as tokens, handles, and properties.
The sample requires a native loopback mode (NLB) test image to be loaded on the FPGA. Refer to Quick Start Guide for full instructions on building, configuring, and running this code sample.
Data Structure Documentation
struct cache_line
Definition at line 85 of file hello_afu.c.
Data Fields
uint32_t
uint[16]
struct config
Definition at line 127 of file hello_fpga.c.
Data Fields
struct target
target
int
open_flags
int
run_n3000
int
bus
float
interval_sec
struct config::target
Definition at line 128 of file hello_fpga.c.
Data Fields
int
bus
Macro Definition Documentation
TEST_TIMEOUT
#define TEST_TIMEOUT 30000
Definition at line 66 of file hello_fpga.c.
CL
#define CL(x) ((x) * 64)
Definition at line 70 of file hello_fpga.c.
LOG2_CL
#define LOG2_CL 6
Definition at line 73 of file hello_fpga.c.
MB
#define MB(x) ((x) * 1024 * 1024)
Definition at line 76 of file hello_fpga.c.
CACHELINE_ALIGNED_ADDR
#define CACHELINE_ALIGNED_ADDR(p) ((p) >> LOG2_CL)
Definition at line 79 of file hello_fpga.c.
LPBK1_BUFFER_SIZE
#define LPBK1_BUFFER_SIZE MB(1)
Definition at line 81 of file hello_fpga.c.
LPBK1_BUFFER_ALLOCATION_SIZE
#define LPBK1_BUFFER_ALLOCATION_SIZE MB(2)
Definition at line 82 of file hello_fpga.c.
LPBK1_DSM_SIZE
#define LPBK1_DSM_SIZE MB(2)
Definition at line 83 of file hello_fpga.c.
CSR_SRC_ADDR
#define CSR_SRC_ADDR 0x0120
Definition at line 84 of file hello_fpga.c.
CSR_DST_ADDR
#define CSR_DST_ADDR 0x0128
Definition at line 85 of file hello_fpga.c.
CSR_CTL
#define CSR_CTL 0x0138
Definition at line 86 of file hello_fpga.c.
CSR_STATUS1
#define CSR_STATUS1 0x0168
Definition at line 87 of file hello_fpga.c.
CSR_CFG
#define CSR_CFG 0x0140
Definition at line 88 of file hello_fpga.c.
CSR_NUM_LINES
#define CSR_NUM_LINES 0x0130
Definition at line 89 of file hello_fpga.c.
DSM_STATUS_TEST_COMPLETE
#define DSM_STATUS_TEST_COMPLETE 0x40
Definition at line 90 of file hello_fpga.c.
CSR_AFU_DSM_BASEL
#define CSR_AFU_DSM_BASEL 0x0110
Definition at line 91 of file hello_fpga.c.
NLB0_AFUID
#define NLB0_AFUID `D8424DC4-A4A3-C413-F89E-433683F9040B`
Definition at line 94 of file hello_fpga.c.
N3000_AFUID
#define N3000_AFUID `9AEFFE5F-8457-0612-C000-C9660D824272`
Definition at line 97 of file hello_fpga.c.
FPGA_NLB0_UUID_H
#define FPGA_NLB0_UUID_H 0xd8424dc4a4a3c413
Definition at line 98 of file hello_fpga.c.
FPGA_NLB0_UUID_L
#define FPGA_NLB0_UUID_L 0xf89e433683f9040b
Definition at line 99 of file hello_fpga.c.
ON_ERR_GOTO
#define ON_ERR_GOTO(res, label, desc)
Value:
   do { \
      if ((res) != FPGA_OK) { \
         print_err((desc), (res)); \
         goto label; \
      } \
   } while (0)
Definition at line 106 of file hello_fpga.c.
GETOPT_STRING
#define GETOPT_STRING `B:scv`
Definition at line 143 of file hello_fpga.c.
Function Documentation
usleep()
int usleep (unsigned)
Referenced by main().
print_err()
void print_err (const char * s, fpga_result res)
Definition at line 119 of file hello_fpga.c.
References fpgaErrStr().
parse_args()
fpga_result parse_args (int argc, char * argv[])
Definition at line 144 of file hello_fpga.c.
References config::target::bus, FPGA_EXCEPTION, FPGA_OK, FPGA_OPEN_SHARED, fpgaGetOPAECBuildString(), fpgaGetOPAECVersionString(), GETOPT_STRING, config::open_flags, config::run_n3000, and config::target.
Referenced by main().
find_fpga()
fpga_result find_fpga (fpga_guid afu_guid, fpga_token * accelerator_token, uint32_t * num_matches_accelerators)
Definition at line 202 of file hello_fpga.c.
References config::target::bus, FPGA_ACCELERATOR, FPGA_OK, fpgaDestroyProperties(), fpgaEnumerate(), fpgaGetProperties(), fpgaPropertiesSetBus(), fpgaPropertiesSetGUID(), fpgaPropertiesSetObjectType(), ON_ERR_GOTO, and config::target.
Referenced by main().
get_bus()
fpga_result get_bus (fpga_token tok, uint8_t * bus)
Definition at line 235 of file hello_fpga.c.
References FPGA_OK, fpgaDestroyProperties(), fpgaGetProperties(), fpgaPropertiesGetBus(), and ON_ERR_GOTO.
Referenced by main().
probe_for_ase()
bool probe_for_ase (void)
Definition at line 255 of file hello_fpga.c.
References FPGA_DEVICE, FPGA_OK, fpgaDestroyProperties(), fpgaDestroyToken(), fpgaEnumerate(), fpgaGetProperties(), fpgaPropertiesGetDeviceID(), and fpgaPropertiesSetObjectType().
Referenced by main().
find_nlb_n3000()
fpga_result find_nlb_n3000 (fpga_handle accelerator_handle, uint64_t * afu_baddr)
Definition at line 282 of file hello_fpga.c.
References FPGA_EXCEPTION, FPGA_NLB0_UUID_H, FPGA_NLB0_UUID_L, FPGA_OK, fpgaReadMMIO64(), and ON_ERR_GOTO.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 334 of file hello_fpga.c.
References CACHELINE_ALIGNED_ADDR, CL, CSR_AFU_DSM_BASEL, CSR_CFG, CSR_CTL, CSR_DST_ADDR, CSR_NUM_LINES, CSR_SRC_ADDR, CSR_STATUS1, DSM_STATUS_TEST_COMPLETE, find_fpga(), find_nlb_n3000(), FPGA_EXCEPTION, FPGA_NOT_FOUND, FPGA_OK, fpgaClose(), fpgaDestroyToken(), fpgaGetIOAddress(), fpgaMapMMIO(), fpgaOpen(), fpgaPrepareBuffer(), fpgaReadMMIO64(), fpgaReleaseBuffer(), fpgaReset(), fpgaUnmapMMIO(), fpgaWriteMMIO32(), fpgaWriteMMIO64(), get_bus(), LPBK1_BUFFER_ALLOCATION_SIZE, LPBK1_BUFFER_SIZE, LPBK1_DSM_SIZE, N3000_AFUID, NLB0_AFUID, ON_ERR_GOTO, config::open_flags, parse_args(), probe_for_ase(), config::run_n3000, TEST_TIMEOUT, cache_line::uint, and usleep().
Variable Documentation
config
struct config config
Initial value:
= {
   .target = {
      .bus = -1,
   },
   .open_flags = 0,
   .run_n3000 = 0
}