.TH "samples Directory Reference" 3 "Wed Dec 9 2020" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBbase\fP"
.br
.ti -1c
.RI "directory \fBdummy_afu\fP"
.br
.ti -1c
.RI "directory \fBhello_afu\fP"
.br
.ti -1c
.RI "directory \fBhello_events\fP"
.br
.ti -1c
.RI "directory \fBhello_fpga\fP"
.br
.ti -1c
.RI "directory \fBhello_mpf_afu\fP"
.br
.ti -1c
.RI "directory \fBhssi\fP"
.br
.ti -1c
.RI "directory \fBobject_api\fP"
.br
.in -1c
