.TH "samples/hello_mpf_afu/sw Directory Reference" 3 "Wed Dec 16 2020" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/hello_mpf_afu/sw Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBafu_json_info\&.h\fP"
.br
.ti -1c
.RI "file \fBhello_mpf_afu\&.cpp\fP"
.br
.in -1c
