.TH "samples/base/sw/csr_mgr.h" 3 "Wed Dec 16 2020" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/base/sw/csr_mgr.h
.SH SYNOPSIS
.br
.PP
\fC#include 'opae_svc_wrapper\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCSR_MGR\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
