.TH "hssi_10g_cmd" 3 "Wed Dec 9 2020" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hssi_10g_cmd
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </root/samples/hssi/hssi_10g_cmd\&.h>\fP
.PP
Inherits \fBhssi_cmd\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhssi_10g_cmd\fP ()"
.br
.ti -1c
.RI "virtual const char * \fBname\fP () const override"
.br
.ti -1c
.RI "virtual const char * \fBdescription\fP () const override"
.br
.ti -1c
.RI "virtual void \fBadd_options\fP (CLI::App *\fBapp\fP) override"
.br
.ti -1c
.RI "virtual int \fBrun\fP (\fBtest_afu\fP *afu, CLI::App *\fBapp\fP) override"
.br
.ti -1c
.RI "virtual const char * \fBafu_id\fP () const override"
.br
.ti -1c
.RI "std::ostream & \fBprint_registers\fP (std::ostream &os, \fBhssi_afu\fP *hafu) const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBport_\fP"
.br
.ti -1c
.RI "std::string \fBeth_loopback_\fP"
.br
.ti -1c
.RI "uint32_t \fBnum_packets_\fP"
.br
.ti -1c
.RI "std::string \fBrandom_length_\fP"
.br
.ti -1c
.RI "std::string \fBrandom_payload_\fP"
.br
.ti -1c
.RI "uint32_t \fBpacket_length_\fP"
.br
.ti -1c
.RI "std::string \fBsrc_addr_\fP"
.br
.ti -1c
.RI "std::string \fBdest_addr_\fP"
.br
.ti -1c
.RI "uint32_t \fBrnd_seed0_\fP"
.br
.ti -1c
.RI "uint32_t \fBrnd_seed1_\fP"
.br
.ti -1c
.RI "uint32_t \fBrnd_seed2_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 53 of file hssi_10g_cmd\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "hssi_10g_cmd::hssi_10g_cmd ()\fC [inline]\fP"

.PP
Definition at line 56 of file hssi_10g_cmd\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual const char* hssi_10g_cmd::name () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Definition at line 70 of file hssi_10g_cmd\&.h\&.
.SS "virtual const char* hssi_10g_cmd::description () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Definition at line 75 of file hssi_10g_cmd\&.h\&.
.SS "virtual void hssi_10g_cmd::add_options (CLI::App * app)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Definition at line 80 of file hssi_10g_cmd\&.h\&.
.PP
References app, dest_addr_, eth_loopback_, num_packets_, packet_length_, port_, random_length_, random_payload_, rnd_seed0_, rnd_seed1_, rnd_seed2_, and src_addr_\&.
.SS "virtual int hssi_10g_cmd::run (\fBtest_afu\fP * afu, CLI::App * app)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Definition at line 127 of file hssi_10g_cmd\&.h\&.
.PP
References app, CSR_DEST_ADDR0, CSR_DEST_ADDR1, CSR_MAC_LOOP, CSR_NUM_PACKETS, CSR_PACKET_LENGTH, CSR_PACKET_TX_COUNT, CSR_RANDOM_LENGTH, CSR_RANDOM_PAYLOAD, CSR_RND_SEED0, CSR_RND_SEED1, CSR_RND_SEED2, CSR_SRC_ADDR0, CSR_SRC_ADDR1, CSR_START, CSR_STOP, dest_addr_, hssi_cmd::enable_eth_loopback(), eth_loopback_, hssi_afu::ethernet_interface(), INVALID_MAC, hssi_cmd::mac_bits_for(), hssi_afu::mbox_read(), hssi_afu::mbox_write(), num_packets_, packet_length_, port_, print_registers(), random_length_, random_payload_, rnd_seed0_, rnd_seed1_, rnd_seed2_, hssi_cmd::running_, hssi_cmd::show_eth_stats(), src_addr_, and TRAFFIC_CTRL_PORT_SEL\&.
.SS "virtual const char* hssi_10g_cmd::afu_id () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Definition at line 215 of file hssi_10g_cmd\&.h\&.
.SS "std::ostream& hssi_10g_cmd::print_registers (std::ostream & os, \fBhssi_afu\fP * hafu) const\fC [inline]\fP"

.PP
Definition at line 220 of file hssi_10g_cmd\&.h\&.
.PP
References AFU_SCRATCHPAD, CSR_AVST_RX_ERR, CSR_DEST_ADDR0, CSR_DEST_ADDR1, CSR_MAC_LOOP, CSR_NUM_PACKETS, CSR_NUM_PKT, CSR_PACKET_LENGTH, CSR_PACKET_TX_COUNT, CSR_PKT_BAD, CSR_PKT_GOOD, CSR_RANDOM_LENGTH, CSR_RANDOM_PAYLOAD, CSR_RND_SEED0, CSR_RND_SEED1, CSR_RND_SEED2, CSR_SRC_ADDR0, CSR_SRC_ADDR1, CSR_START, CSR_STOP, ETH_AFU_DFH, ETH_AFU_ID_H, ETH_AFU_ID_L, hssi_cmd::int_to_hex(), hssi_afu::mbox_read(), TRAFFIC_CTRL_CMD, TRAFFIC_CTRL_DATA, and TRAFFIC_CTRL_PORT_SEL\&.
.PP
Referenced by run()\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t hssi_10g_cmd::port_\fC [protected]\fP"

.PP
Definition at line 284 of file hssi_10g_cmd\&.h\&.
.PP
Referenced by add_options(), and run()\&.
.SS "std::string hssi_10g_cmd::eth_loopback_\fC [protected]\fP"

.PP
Definition at line 285 of file hssi_10g_cmd\&.h\&.
.PP
Referenced by add_options(), and run()\&.
.SS "uint32_t hssi_10g_cmd::num_packets_\fC [protected]\fP"

.PP
Definition at line 286 of file hssi_10g_cmd\&.h\&.
.PP
Referenced by add_options(), and run()\&.
.SS "std::string hssi_10g_cmd::random_length_\fC [protected]\fP"

.PP
Definition at line 287 of file hssi_10g_cmd\&.h\&.
.PP
Referenced by add_options(), and run()\&.
.SS "std::string hssi_10g_cmd::random_payload_\fC [protected]\fP"

.PP
Definition at line 288 of file hssi_10g_cmd\&.h\&.
.PP
Referenced by add_options(), and run()\&.
.SS "uint32_t hssi_10g_cmd::packet_length_\fC [protected]\fP"

.PP
Definition at line 289 of file hssi_10g_cmd\&.h\&.
.PP
Referenced by add_options(), and run()\&.
.SS "std::string hssi_10g_cmd::src_addr_\fC [protected]\fP"

.PP
Definition at line 290 of file hssi_10g_cmd\&.h\&.
.PP
Referenced by add_options(), and run()\&.
.SS "std::string hssi_10g_cmd::dest_addr_\fC [protected]\fP"

.PP
Definition at line 291 of file hssi_10g_cmd\&.h\&.
.PP
Referenced by add_options(), and run()\&.
.SS "uint32_t hssi_10g_cmd::rnd_seed0_\fC [protected]\fP"

.PP
Definition at line 292 of file hssi_10g_cmd\&.h\&.
.PP
Referenced by add_options(), and run()\&.
.SS "uint32_t hssi_10g_cmd::rnd_seed1_\fC [protected]\fP"

.PP
Definition at line 293 of file hssi_10g_cmd\&.h\&.
.PP
Referenced by add_options(), and run()\&.
.SS "uint32_t hssi_10g_cmd::rnd_seed2_\fC [protected]\fP"

.PP
Definition at line 294 of file hssi_10g_cmd\&.h\&.
.PP
Referenced by add_options(), and run()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
