.TH "samples/hssi/hssi_cmd.h" 3 "Wed Dec 9 2020" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/hssi/hssi_cmd.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <netinet/ether\&.h>\fP
.br
\fC#include 'afu_test\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBhssi_cmd\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINVALID_MAC\fP   0xffffffffffffffffULL"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBtest_command\fP = opae::afu_test::command"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INVALID_MAC   0xffffffffffffffffULL"

.PP
Definition at line 36 of file hssi_cmd\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "using \fBtest_command\fP =  opae::afu_test::command"

.PP
Definition at line 34 of file hssi_cmd\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
