.TH "samples/hssi/hssi_100g_cmd.h" 3 "Wed Dec 16 2020" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/hssi/hssi_100g_cmd.h
.SH SYNOPSIS
.br
.PP
\fC#include 'hssi_cmd\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBhssi_100g_cmd\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCSR_SCRATCH\fP   0x1000"
.br
.ti -1c
.RI "#define \fBCSR_FEATURES\fP   0x1002"
.br
.ti -1c
.RI "#define \fBCSR_CTRL0\fP   0x1009"
.br
.ti -1c
.RI "#define \fBCSR_CTRL1\fP   0x1010"
.br
.ti -1c
.RI "#define \fBCSR_DST_ADDR_LO\fP   0x1011"
.br
.ti -1c
.RI "#define \fBCSR_DST_ADDR_HI\fP   0x1012"
.br
.ti -1c
.RI "#define \fBCSR_SRC_ADDR_LO\fP   0x1013"
.br
.ti -1c
.RI "#define \fBCSR_SRC_ADDR_HI\fP   0x1014"
.br
.ti -1c
.RI "#define \fBCSR_MLB_RST\fP   0x1016"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CSR_SCRATCH   0x1000"

.PP
Definition at line 29 of file hssi_100g_cmd\&.h\&.
.SS "#define CSR_FEATURES   0x1002"

.PP
Definition at line 30 of file hssi_100g_cmd\&.h\&.
.SS "#define CSR_CTRL0   0x1009"

.PP
Definition at line 31 of file hssi_100g_cmd\&.h\&.
.SS "#define CSR_CTRL1   0x1010"

.PP
Definition at line 32 of file hssi_100g_cmd\&.h\&.
.SS "#define CSR_DST_ADDR_LO   0x1011"

.PP
Definition at line 33 of file hssi_100g_cmd\&.h\&.
.SS "#define CSR_DST_ADDR_HI   0x1012"

.PP
Definition at line 34 of file hssi_100g_cmd\&.h\&.
.SS "#define CSR_SRC_ADDR_LO   0x1013"

.PP
Definition at line 35 of file hssi_100g_cmd\&.h\&.
.SS "#define CSR_SRC_ADDR_HI   0x1014"

.PP
Definition at line 36 of file hssi_100g_cmd\&.h\&.
.SS "#define CSR_MLB_RST   0x1016"

.PP
Definition at line 37 of file hssi_100g_cmd\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
