.TH "samples/base/sw/opae_svc_wrapper.cpp" 3 "Wed Dec 9 2020" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/base/sw/opae_svc_wrapper.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <uuid/uuid\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'opae_svc_wrapper\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
