.TH "samples/base/sw/opae_svc_wrapper.h" 3 "Wed Dec 16 2020" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/base/sw/opae_svc_wrapper.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <opae/fpga\&.h>\fP
.br
\fC#include <opae/mpf/mpf\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBOPAE_SVC_WRAPPER\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef class \fBOPAE_SVC_WRAPPER\fP \fBSVC_WRAPPER\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef class \fBOPAE_SVC_WRAPPER\fP \fBSVC_WRAPPER\fP"

.PP
Definition at line 37 of file opae_svc_wrapper\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
