name: C/C++ CI

on:
  push:
    paths: ['**.c', '**.h', '**.cpp', '**CMakeLists.txt', '**.yml']
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Get Package
      uses: mstksg/get-package@v1
      with:
        apt-get: uuid-dev libjson-c-dev libhwloc-dev    
    - name: configure
      run: mkdir build && pushd build && cmake .. -DBUILD_TESTS=ON && popd
    - name: build
      run: pushd build && make && popd
    - name: test
      run: pushd build && make test && popd
