name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Get Package
      uses: mstksg/get-package@v1
      with:
        apt-get: uuid-dev      
    - name: configure
      run: mkdir build && pushd build && cmake .. && make

