name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Packages
      run: apt install update && apt install snapd && snap install skopeo
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest
    - name: save
      run: docker images && docker save my-image-name:latest | gzip > my-image.tar.gz
    - name: Archive production artifacts 
      uses: actions/upload-artifact@v1
      with:
        name: my-image
        path: my-image.tar.gz
