name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Packages
      run: sudo apt update && sudo apt install snapd && sudo snap install --edge --devmode skopeo
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest
    - name: Save Docker Image
      run: docker images && docker save my-image-name:latest > my-image.tar
    - name: Convert to OCI bundle
      run: skopeo copy docker-archive:my-image.tar oci:my-image-oci
    - name: Tar OCI image
      run: tar -czvf my-image-oci.tar.gz my-image-oci
    - name: Archive production artifacts 
      uses: actions/upload-artifact@v1
      with:
        name: my-image-oci
        path: my-image-oci.tar.gz
